{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.webviewflutter",
    "module": "webview_flutter_android_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-e4b8dca3f1b4ede4c30371002441c88c12187ed6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "webview_flutter_android_release-1.0.aar",
          "url": "webview_flutter_android_release-1.0.aar",
          "size": 266250,
          "sha512": "02d4bbef4ca44be232570e2e1970b2a99aee512a28baaf102dafc294767e26b29cbaf307633e8309cae73630c469c4d4b258557768c198b7ac222734aa71f4c4",
          "sha256": "6a2d4d27fb5e66c5d5a02e4d02b10fbe22a88efbee1420c996eb5a8b477b4e80",
          "sha1": "cd88b2dffa15d6874344026e2af8b2817575490a",
          "md5": "1aeaff6f0cf8b5ac06401cca2cda7c1d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-e4b8dca3f1b4ede4c30371002441c88c12187ed6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "webview_flutter_android_release-1.0.aar",
          "url": "webview_flutter_android_release-1.0.aar",
          "size": 266250,
          "sha512": "02d4bbef4ca44be232570e2e1970b2a99aee512a28baaf102dafc294767e26b29cbaf307633e8309cae73630c469c4d4b258557768c198b7ac222734aa71f4c4",
          "sha256": "6a2d4d27fb5e66c5d5a02e4d02b10fbe22a88efbee1420c996eb5a8b477b4e80",
          "sha1": "cd88b2dffa15d6874344026e2af8b2817575490a",
          "md5": "1aeaff6f0cf8b5ac06401cca2cda7c1d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "webview_flutter_android_release-1.0-sources.jar",
          "url": "webview_flutter_android_release-1.0-sources.jar",
          "size": 61256,
          "sha512": "e3db1dce34c386ce779888a190e84c5f72e7dd021cacb1f763168532618a880d7ff0ee468906838adb7e42014874c9ba4f9242269b5490489992edb597961436",
          "sha256": "00584e3f73376120584215cc456a80948d2d9e252aa9b1af928063244eae7c0d",
          "sha1": "aa4fb2c895a8a19e0caae6d391614eba954d2d9c",
          "md5": "2fed686b26cea8a297d9479369d5867a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "webview_flutter_android_release-1.0-javadoc.jar",
          "url": "webview_flutter_android_release-1.0-javadoc.jar",
          "size": 750349,
          "sha512": "f477758ac79ddb5a1d30e0315b9c554ce1b111605e16d89fb51f55cdf0cb4b76ca0114f046c9748fcff3336bf9e2551d782a7b09912ae0e699ef79297f8f5eba",
          "sha256": "eb3d76a233159b02a697fef469bcf84fa818b189700171e4d6bad2502c105c6a",
          "sha1": "504f0e09f79d08dca1a32fcafe2ea483b8170f5f",
          "md5": "034d5953af964d29494e4b8b440db453"
        }
      ]
    }
  ]
}
