{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mr.flutter.plugin.filepicker",
    "module": "file_picker_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-e4b8dca3f1b4ede4c30371002441c88c12187ed6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "file_picker_release-1.0.aar",
          "url": "file_picker_release-1.0.aar",
          "size": 40854,
          "sha512": "c629405b3ea6a2859ce3d8a6f78dea823b940559509fe1947fc18c9b33ffcf9566be8eeb26ed396f75fb660ed0a98c0d26ef962097e7fe69a897dde71d3ea771",
          "sha256": "956e1ab48e6ec3f92ac3a3eedf6bdbcd9ddc24003275581633682cfa928b4186",
          "sha1": "6d2ea2e645a6d6d03cdada53113e65fc1c599674",
          "md5": "3b2329dd32bdde9d0f29db41c5aa3845"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-e4b8dca3f1b4ede4c30371002441c88c12187ed6"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "org.apache.tika",
          "module": "tika-core",
          "version": {
            "requires": "3.2.3"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "file_picker_release-1.0.aar",
          "url": "file_picker_release-1.0.aar",
          "size": 40854,
          "sha512": "c629405b3ea6a2859ce3d8a6f78dea823b940559509fe1947fc18c9b33ffcf9566be8eeb26ed396f75fb660ed0a98c0d26ef962097e7fe69a897dde71d3ea771",
          "sha256": "956e1ab48e6ec3f92ac3a3eedf6bdbcd9ddc24003275581633682cfa928b4186",
          "sha1": "6d2ea2e645a6d6d03cdada53113e65fc1c599674",
          "md5": "3b2329dd32bdde9d0f29db41c5aa3845"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "file_picker_release-1.0-sources.jar",
          "url": "file_picker_release-1.0-sources.jar",
          "size": 12064,
          "sha512": "c67e8390459cd050f33dd6dd5f2625dc490387f9b0c2bd37253fd443f1e01e671a7fd87be2108d84a922e987e6e83a1ebdf3ff87fb3b421bf6d93663d0665b4e",
          "sha256": "b803064682c92fe74396755dae060fd99ec41636bf71a903139647ed7b12d95c",
          "sha1": "511a272d6dcde5f4c8b7ebed969ccff8ff25cfa0",
          "md5": "03c8146702dccc9d55f323de6a628f06"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "file_picker_release-1.0-javadoc.jar",
          "url": "file_picker_release-1.0-javadoc.jar",
          "size": 307965,
          "sha512": "337c57d0a7248db127cdeb7a568f7e32d974cdb2f44cf2834628add13af0c4602edb6729b3733160173896b2f54429d86e2890c46be7fe2891b1e3169758faef",
          "sha256": "6c9bb79cfc62ccd1bc55c210e8c356c5f0e1b03298d00dd0f3b20bd5bc391ff6",
          "sha1": "d391e6f939887bbf898bfa4b38db9012a36783fd",
          "md5": "407112a7c76cb3809f7ed6f71278b3d4"
        }
      ]
    }
  ]
}
